### ISSUE TITLE
OVMF fails to boot with SMP enabled

### ISSUE THREAD

**Issue by jboeing** [tianocore/edk2#80] opened 2016-04-16 21:24 UTC
If I enable SMP in my VM, QEMU either hangs at boot or dies with the error message:
`
KVM: entry failed, hardware error 0x80000021`

I git-bisected the failure to commit 94941c8: UefiCpuPkg: CpuDxe: broadcast MTRR changes to APs

The host is running Linux kernel 4.4.6 and QEMU 2.5.0.  The host is using GCC 5.3.0; I get the same failure whether I build OVMF with GCC 4.9.3 or 5.3.0.  A minimal QEMU command line to repro is:

qemu-system-x86_64 -enable-kvm -smp cpus=2 -drive if=pflash,format=raw,file=OVMF.fd

Here's the output from the debug build of OVMF:

```
SecCoreStartupWithStack(0xFFFCC000, 0x818000)
Register PPI Notify: DCD0BE23-9586-40F4-B643-06522CED4EDE
Install PPI: 8C8CE578-8A3D-4F1C-9935-896185C32DD3
Install PPI: 5473C07A-3DCB-4DCA-BD6F-1E9689E7349A
The 0th FV start address is 0x00000820000, size is 0x000E0000, handle is 0x820000
Register PPI Notify: 49EDB1C1-BF21-4761-BB12-EB0031AABB39
Register PPI Notify: EA7CA24B-DED5-4DAD-A389-BF827E8F9B38
Install PPI: B9E0ABFE-5979-4914-977F-6DEE78C278A6
Install PPI: DBE23AA9-A345-4B97-85B6-B226F1617389
Loading PEIM at 0x00000839BC0 EntryPoint=0x00000839E00 PcdPeim.efi
Install PPI: 06E81C58-4AD7-44BC-8390-F10265F72480
Install PPI: 01F34D25-4DE2-23AD-3FF3-36353FF323F1
Install PPI: 4D8B155B-C059-4C8F-8926-06FD4331DB8A
Install PPI: A60C6B59-E459-425D-9C69-0BCC9CB27D81
Loading PEIM at 0x000008435C0 EntryPoint=0x00000843800 StatusCodePei.efi
Install PPI: 229832D3-7A30-4B36-B827-F40CB7D45436
Loading PEIM at 0x000008491C0 EntryPoint=0x00000849400 PlatformPei.efi
Select Item: 0x0
FW CFG Signature: 0x554D4551
Select Item: 0x1
FW CFG Revision: 0x3
QemuFwCfg interface is supported.
Platform PEIM Loaded
CMOS:
00: 25 00 17 00 21 00 07 16 04 16 26 02 00 80 00 00
10: 40 00 00 00 07 80 02 FF FF 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
30: FF FF 20 00 00 07 00 20 30 00 00 00 00 12 00 00
40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01
60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Select Item: 0x19
Select Item: 0x25
S3 support was detected on QEMU
Install PPI: 7408D748-FC8C-4EE6-9288-C4BEC092A410
PublishPeiMemory: mPhysMemAddressWidth=36 PeiMemoryCap=65800 KB
PeiInstallPeiMemory MemoryBegin 0x3FBE000, MemoryLength 0x4042000
QemuInitializeRam called
Allocated Memory unaligned: Address = 0x7FD0000, Pages = 0x30, Type = 6 
After aligning to 0x10000 bytes: Address = 0x7FD0000, Pages = 0x20 
Updated aligned-mem HOB with BaseAddress = 7FD0000, Length = 20000, MemoryType = 6 
Created after-mem HOB with BaseAddress = 7FF0000, Length = 10000, MemoryType = 7 
Reserved variable store memory: 0x7FD0000; size: 128kb
Platform PEI Firmware Volume Initialization
Install PPI: 49EDB1C1-BF21-4761-BB12-EB0031AABB39
Notify: PPI Guid: 49EDB1C1-BF21-4761-BB12-EB0031AABB39, Peim notify entry point: 82491E
The 1th FV start address is 0x00000900000, size is 0x00900000, handle is 0x900000
Select Item: 0x19
Select Item: 0x19
Temp Stack : BaseAddress=0x814000 Length=0x4000
Temp Heap  : BaseAddress=0x810000 Length=0x19E0
Total temporary memory:    32768 bytes.
  temporary memory stack ever used: 16384 bytes.
  temporary memory heap used:       6624 bytes.
Old Stack size 16384, New stack size 131072
Stack Hob: BaseAddress=0x3FBE000 Length=0x20000
Heap Offset = 0x37CE000 Stack Offset = 0x37C6000
TemporaryRamMigration(0x810000, 0x3FDA000, 0x8000)
Loading PEIM at 0x00007FB5000 EntryPoint=0x00007FB5240 PeiCore.efi
Reinstall PPI: 8C8CE578-8A3D-4F1C-9935-896185C32DD3
Reinstall PPI: 5473C07A-3DCB-4DCA-BD6F-1E9689E7349A
Reinstall PPI: B9E0ABFE-5979-4914-977F-6DEE78C278A6
Install PPI: F894643D-C449-42D1-8EA8-85BDD8C65BDE
Loading PEIM at 0x00007FAA000 EntryPoint=0x00007FAA240 DxeIpl.efi
Install PPI: 0AE8CE5D-E448-4437-A8D7-EBF5F194F731
Install PPI: 1A36E4E7-FAB6-476A-8E75-695A0576FDD7
Loading PEIM at 0x00007F9F000 EntryPoint=0x00007F9F240 S3Resume2Pei.efi
Install PPI: 6D582DBC-DB85-4514-8FCC-5ADF6227B147
DXE IPL Entry
Loading PEIM at 0x00007F5C000 EntryPoint=0x00007F5C240 DxeCore.efi
Loading DXE CORE at 0x00007F5C000 EntryPoint=0x00007F5C240
Install PPI: 605EA650-C65C-42E1-BA80-91A52AB618C6
CoreInitializeMemoryServices:
  BaseAddress - 0x3FE0000 Length - 0x3F1A000 MinimalMemorySizeNeeded - 0x10F4000
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 7F98668
HOBLIST address in DXE = 0x7D11018
Memory Allocation 0x0000000A 0x818000 - 0x81FFFF
Memory Allocation 0x0000000A 0x810000 - 0x817FFF
Memory Allocation 0x0000000A 0x807000 - 0x807FFF
Memory Allocation 0x0000000A 0x800000 - 0x805FFF
Memory Allocation 0x0000000A 0x806000 - 0x806FFF
Memory Allocation 0x00000006 0x7FD0000 - 0x7FEFFFF
Memory Allocation 0x00000007 0x7FF0000 - 0x7FFFFFF
Memory Allocation 0x0000000A 0x820000 - 0x8FFFFF
Memory Allocation 0x00000004 0x900000 - 0x11FFFFF
Memory Allocation 0x00000004 0x7F3C000 - 0x7F5BFFF
Memory Allocation 0x00000004 0x7FCF000 - 0x7FCFFFF
Memory Allocation 0x00000004 0x7FB5000 - 0x7FCEFFF
Memory Allocation 0x00000004 0x7FAA000 - 0x7FB4FFF
Memory Allocation 0x00000004 0x7F9F000 - 0x7FA9FFF
Memory Allocation 0x00000004 0x7F5C000 - 0x7F9EFFF
Memory Allocation 0x00000003 0x7F5C000 - 0x7F9EFFF
Memory Allocation 0x00000004 0x7F3C000 - 0x7F5BFFF
Memory Allocation 0x00000004 0x7EFA000 - 0x7F3BFFF
Memory Allocation 0x00000004 0x3FBE000 - 0x3FDDFFF
FV Hob            0x900000 - 0x11FFFFF
InstallProtocolInterface: D8117CFE-94A6-11D4-9A3A-0090273FC14D 7F985F0
InstallProtocolInterface: 8F644FA9-E850-4DB1-9CE2-0B44698E8DA4 7D0D270
InstallProtocolInterface: 09576E91-6D3F-11D2-8E39-00A0C969723B 7D0D658
InstallProtocolInterface: 220E73B6-6BDB-4413-8405-B974B108619A 7D0BE70
InstallProtocolInterface: EE4E5898-3914-4259-9D6E-DC7BD79403CF 7F98610
Loading driver 9B680FCE-AD6B-4F3A-B60B-F59899003443
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 77FCA80
Loading driver at 0x00007E81000 EntryPoint=0x00007E8128F DevicePathDxe.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 77FCCD8
InstallProtocolInterface: 0379BE4E-D706-437D-B037-EDB82FB772A4 7E8F640
InstallProtocolInterface: 8B843E20-8132-4852-90CC-551A4E4A7F1C 7E8F680
InstallProtocolInterface: 05C99A21-C70F-4AD2-8A5F-35DF3343F51E 7E8F690
Loading driver 80CF7257-87AB-47F9-A3FE-D50B76D89541
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 77EE040
Loading driver at 0x00007E74000 EntryPoint=0x00007E7428F PcdDxe.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 77EE218
InstallProtocolInterface: 11B34006-D85B-4D0A-A290-D5A571310EF7 7E7FD40
InstallProtocolInterface: 13A3F0F6-264A-3EF0-F2E0-DEC512342F34 7E7FE40
InstallProtocolInterface: 5BE40F57-FA68-4610-BBBF-E9C5FCDAD365 7E7FED0
InstallProtocolInterface: FD0F4478-0EFD-461D-BA2D-E58C45FD5F5E 7E7FEF0
Loading driver 733CBAC2-B23F-4B92-BC8E-FB01CE5907B7
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 77FB0C0
Loading driver at 0x00007EB9000 EntryPoint=0x00007EBA04F FvbServicesRuntimeDxe.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 77FBD98
QEMU Flash: Attempting flash detection at FFE00010
QemuFlashDetected => FD behaves as FLASH
QemuFlashDetected => Yes
Installing QEMU flash FVB
InstallProtocolInterface: 8F644FA9-E850-4DB1-9CE2-0B44698E8DA4 7EE8DF0
InstallProtocolInterface: 09576E91-6D3F-11D2-8E39-00A0C969723B 77FBA58
Loading driver FEDE0A1B-BCA2-4A9F-BB2B-D9FD7DEC2E9F
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 77F8040
Loading driver at 0x00007EAD000 EntryPoint=0x00007EAE04F StatusCodeRuntimeDxe.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 77F8218
InstallProtocolInterface: D2B2B828-0826-48A7-B3DF-983C006024F0 7EB7000
Loading driver B601F8C4-43B7-4784-95B1-F4226CB40CEE
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 77F8400
Loading driver at 0x00007EA3000 EntryPoint=0x00007EA404F RuntimeDxe.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 77F8658
InstallProtocolInterface: B7DFB4E1-052F-449F-87BE-9818FC91B733 7EAB000
Loading driver F80697E9-7FD6-4665-8646-88E33EF71DFC
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 77F7C80
Loading driver at 0x00007E6E000 EntryPoint=0x00007E6E28F SecurityStubDxe.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 77F7A58
InstallProtocolInterface: 94AB2F58-1438-4EF1-9152-18941A3A0E68 7E73788
InstallProtocolInterface: A46423E3-4617-49F1-B9FF-D1BFA9115839 7E73780
Loading driver 13AC6DD0-73D0-11D4-B06B-00AA00BD6DE7
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 77F7500
Loading driver at 0x00007E62000 EntryPoint=0x00007E6228F EbcDxe.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 77F6018
InstallProtocolInterface: 13AC6DD1-73D0-11D4-B06B-00AA00BD6DE7 77F6D98
InstallProtocolInterface: 2755590C-6F3C-42FA-9EA4-A3BA543CDA25 77F6CD8
InstallProtocolInterface: AAEACCFD-F27B-4C17-B610-75CA1F2DFB52 77F6C98
Loading driver 79CA4208-BBA1-4A9A-8456-E1E66A81484E
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 77F6340
Loading driver at 0x00007E5D000 EntryPoint=0x00007E5D28F Legacy8259.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 77F6518
InstallProtocolInterface: 38321DBA-4FE0-4E17-8AEC-413055EAEDC1 7E61600
Loading driver A19B1FE7-C1BC-49F8-875F-54A5D542443F
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 77F50C0
Loading driver at 0x00007E57000 EntryPoint=0x00007E5728F CpuIo2Dxe.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 77F5B18
InstallProtocolInterface: AD61F191-AE5F-4C0E-B9FA-E869D288C64F 7E5BB80
Loading driver 1A1E4886-9517-440E-9FDE-3BE44CEE2136
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 77F5340
Loading driver at 0x00007E43000 EntryPoint=0x00007E4328F CpuDxe.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 77F5958
InstallProtocolInterface: 26BACCB1-6F42-11D4-BCE7-0080C73C8881 7E54D40
  Flushing GCD
  Flushing GCD
  Flushing GCD
  Flushing GCD
  Flushing GCD
  Flushing GCD
  Flushing GCD
  Flushing GCD
  Flushing GCD
Detect CPU count: 2
Does not find any HOB stored CPU BIST information!
KVM: entry failed, hardware error 0x80000021

If you're running a guest on an Intel machine without unrestricted mode
support, the failure can be most likely due to the guest entering an invalid
state for Intel VT. For example, the guest maybe running in big real mode
which is not supported on less recent Intel processors.

EAX=00000000 EBX=00000000 ECX=00000000 EDX=00000600
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=00000000 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 0000ffff 00009300
CS =9f00 0009f000 0000ffff 00009b00
SS =0000 00000000 0000ffff 00009300
DS =0000 00000000 0000ffff 00009300
FS =0000 00000000 0000ffff 00009300
GS =0000 00000000 0000ffff 00009300
LDT=0000 00000000 0000ffff 00008200
TR =0000 00000000 0000ffff 00008b00
GDT=     00000000 0000ffff
IDT=     00000000 0000ffff
CR0=60000010 CR2=00000000 CR3=07efa000 CR4=00000000
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000000
Code=<eb> 06 3f 00 d8 87 ee 07 fa b8 00 9f 8e d8 bb 02 00 3e 66 0f 01 17 66 b8 23 00 00 00 0f 22 c0 66 ea 27 f0 09 00 10 00 b8 40 06 00 00 0f 22 e0 66 b8 08
```
If booting hangs rather than hits the KVM error, the debug output is the same as above except it cuts off after the "Does not find any HOB stored CPU BIST information!" message.

**Comment by jboeing** [comment] 2016-04-16 21:41
For the record, the same setup boots fine if the only change is to use SeaBIOS instead of OVMF.

**Comment by jboeing** [comment] 2016-04-16 22:48
I forgot to mention that the host in question has a quad-core Intel Penryn CPU (Q9550S).

**Comment by lersek** [comment] 2016-04-18 14:45
Thank you for the report, even though it makes me cry. :( :( :(

Can you please grab (or build) the most recent OVMF available to you, and bisect the host kernel under it, using the stable tree? (I realize this will be horribly annoying, so thank you for your cooperation.)

I'm requesting this because to my knowledge things have been working nicely on 4.4+ host kernels. Namely, the edk2 commit you identified is not new (it is dated Oct 19, 2015). On the other hand, the 4.4.6 stable / longterm kernel is new-ish (Mar 16,2016). I would recommend (more precisely, ask you for) bisecting 4.4.0 through 4.4.6.

Thank you
Laszlo

**Comment by lersek** [comment] 2016-04-18 14:47
... This may be wishful thinking on my part, but it looks like 4.4.6 regressed other virt-related stuff as well; see for example this thread: http://thread.gmane.org/gmane.comp.emulators.qemu/406416

**Comment by lersek** [comment] 2016-04-18 14:50
$ git log --oneline --reverse v4.4.5..v4.4.6 | grep -i kvm
    c9e1bbef7e77 kvm: cap halt polling at exactly halt_poll_ns
    0bbe5fa4f79a KVM: VMX: disable PEBS before a guest entry
    78939530542f KVM: s390: correct fprs on SIGP (STOP AND) STORE STATUS
    1c463a390a89 KVM: PPC: Book3S HV: Sanitize special-purpose register values on guest exit
    68ed2ca153c7 KVM: MMU: fix ept=0/pte.u=1/pte.w=0/CR0.WP=0/CR4.SMEP=1/EFER.NX=0 combo
    1ebd29d6b940 KVM: MMU: fix reserved bit check for ept=0/CR0.WP=0/CR4.SMEP=1/EFER.NX=0

**Comment by lersek** [comment] 2016-04-18 14:57
I've also asked @bonzini for his insight wrt. this report. Thanks!

**Comment by jboeing** [comment] 2016-04-18 15:48
Sure, I'll take a shot at bisecting the host kernel.

In the meantime, I tried using the 94941c8 OVMF build with older kernels I have on the host.  The VM booted with 4.1.6 on the host, but failed with 4.2.0.

**Comment by lersek** [comment] 2016-04-18 16:53
Please don't bother testing pre-4.4.0 hosts. Please see issue 21: hosts kernels >= 4.2 and < 4.4.0 are known to break OVMF.

... Well, actually, I find it useful that you tested 4.1.6. Your successful test suggests that your hardware is "appropriate", and that 4.4.6 has reintroduced similar issues that were fixed from 4.2.0 to 4.4.0.

**Comment by jboeing** [comment] 2016-04-18 18:49
I started bisecting 4.1 to 4.2 before I saw your last comment. It was pointing somewhere in the big KVM merge commit (4e24155) for 4.2-rc1 where I left off.

After looking through #21 and the linked kernel bug (https://bugzilla.kernel.org/show_bug.cgi?id=107561), I tested 4.4.0 (and 4.4.3). I still hit the same failure, so I think I'm seeing something that was missed in the 4.3/4.4 fixes rather than a regression in the 4.4 stable series.

**Comment by lersek** [comment] 2016-04-18 18:58
Thanks for the update.

@bonzini said in <https://github.com/tianocore/edk2/issues/21#issuecomment-174916085>,

> Even with 4.4 there are some changes compared to 4.1 that may cause this bug. 4.4 only fixed the bugs, it didn't revert everything.

That seems to be consistent with your results, yes? 4.1.6 is the last one that works for you, and none of 4.4.0, 4.4.3, and 4.4.6 do. Right?

**Comment by jboeing** [comment] 2016-04-18 19:13
That's right.

**Comment by jboeing** [comment] 2016-04-18 20:53
Finishing the kernel bisect points to commit d28bc9d: `KVM: x86: INIT and reset sequences are different` as where my failure starts.  Commit 5690891: `kvm: x86: zero EFER on INIT` undid a small part of it, but otherwise it seems to be intact on the latest kernel tip.

So...would you suggest reporting a bug against KVM, or wait for @bonzini to chime in?

**Comment by lersek** [comment] 2016-04-19 12:43
Thank you very much for completing the bisection.

I have emailed Paolo directly about this item, but I think he might need two weeks (possibly more) to get to it. Normally I would recommend to just wait until he responds here, but given the time frame (and your precise results with the bisection), I recommend opening a kernel bugzilla.

(In issue #21 too, a kernel BZ got referenced (107561), so this shouldn't count as unusual.)

Once you have a BZ filed in http://bugzilla.kernel.org/, could you please paste the link here? Thank you.

BTW, my colleague Radim has recently become co-maintainer for KVM, so I'm going to ask him to review this item as well. (I'm unsure if Radim has a github ID, which is why the direct email + a kernel BZ might be best.)

Thanks!

**Comment by lersek** [comment] 2016-04-19 15:36
@jboeing, Radim looked at your report, and said

> He has Penryn, which is one of first CPUs that shipped with VMX ... Have you tried running without kvm_intel.ept and/or other parameters?

Which immediately caused me to snap my forehead -- I have already determined that you *need* EPT for this stuff to work. Please refer to the following message:

http://thread.gmane.org/gmane.comp.bios.edk2.devel/9268/focus=9406

The original topic of said thread is different / independent, but the symptoms experienced there, and the cause (lack of EPT) should be identical. Can you please verify if you have EPT support in your host CPU?

... It does remain an interesting question why after KVM commit d28bc9d, EPT became a hard requirement for running OVMF. Anyway, I'll happily defer that question to our kernel developers. @jboeing, after you please file a kernel BZ, and confirm that your phys machine does lack EPT, I believe I'd like to close this OVMF report. Thanks!

**Comment by jboeing** [comment] 2016-04-19 16:42
Penryn doesn't have EPT; that was added for Nehalem.
```
$ cat /proc/cpuinfo
...
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush
dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts
rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm
sse4_1 xsave lahf_lm dtherm tpr_shadow vnmi flexpriority
```
```
$ tail /sys/module/kvm_intel/parameters/*
==> /sys/module/kvm_intel/parameters/emulate_invalid_guest_state <==
Y

==> /sys/module/kvm_intel/parameters/enable_apicv <==
N

==> /sys/module/kvm_intel/parameters/enable_shadow_vmcs <==
N

==> /sys/module/kvm_intel/parameters/ept <==
N

==> /sys/module/kvm_intel/parameters/eptad <==
N

==> /sys/module/kvm_intel/parameters/fasteoi <==
Y

==> /sys/module/kvm_intel/parameters/flexpriority <==
Y

==> /sys/module/kvm_intel/parameters/nested <==
N

==> /sys/module/kvm_intel/parameters/ple_gap <==
0

==> /sys/module/kvm_intel/parameters/ple_window <==
4096

==> /sys/module/kvm_intel/parameters/ple_window_grow <==
2

==> /sys/module/kvm_intel/parameters/ple_window_max <==
1073741823

==> /sys/module/kvm_intel/parameters/ple_window_shrink <==
0

==> /sys/module/kvm_intel/parameters/pml <==
N

==> /sys/module/kvm_intel/parameters/unrestricted_guest <==
N

==> /sys/module/kvm_intel/parameters/vmm_exclusive <==
Y

==> /sys/module/kvm_intel/parameters/vpid <==
N
```
I'm working on the kernel BZ now.

**Comment by jboeing** [comment] 2016-04-19 17:48
https://bugzilla.kernel.org/show_bug.cgi?id=116731

**Comment by lersek** [comment] 2016-04-19 17:56
> https://bugzilla.kernel.org/show_bug.cgi?id=116731

Thank you. I've CC'd @rkrcmar (and myself) on that bug, and I'm closing this one.

**Closed by lersek** 2016-04-19 17:56 UTC
Labels: OVMF

**Comment by lersek** [comment] 2016-07-21 20:05
This (closed) item has been manually migrated to
https://tianocore.acgmultimedia.com/show_bug.cgi?id=83
